var a,b;
a=prompt("Digite um número");
a=parseInt(a);
b=prompt("Digite outro número");
b=parseInt(b);
document.write ("soma: "+ (a+b));
document.write ("<br>subtração: "+ (a-b));
document.write ("<br>multiplicação: "+ (a*b));
document.write ("<br>divisão: "+ (a/b));
document.write ("<br>módulo: "+ (a%b));
document.write ("<br>exponenciação: "+ (a**b));